Backport a625bfdba45d49bc717bcc9be4112db93b50f50a
openjdk/jdk8u-dev pull request #105
Opened 2022-08-18 08:28 UTC by xpbob

Backport a625bfdba45d49bc717bcc9be4112db93b50f50a

2022-08-30 17:41 UTC, jerboaa commented
Only copyright header and path changes. Marking as clean.

2022-08-30 17:41 UTC, jerboaa commented
/clean

2022-08-31 01:53 UTC, xpbob commented
@jerboaa 
Thanks for review

2022-08-31 01:53 UTC, xpbob commented
/integrate

2022-08-31 02:03 UTC, DamonFool commented
/sponsor

2022-08-31 02:09 UTC, xpbob commented
This bug has been flagged jdk8u-fix-yes

2022-08-31 02:16 UTC, gnu-andrew requested changes
Backport looks good.
8u is currently closed for rampdown. Please wait for it to re-open before integrating this patch.

2022-08-31 02:17 UTC, gnu-andrew commented
/reviewers 1 reviewer

2022-09-01 01:14 UTC, gnu-andrew approved these changes
8u-dev is now open for 8u362.

2022-09-01 01:17 UTC, gnu-andrew commented
/sponsor

2022-09-01 01:19 UTC, closed without merging