8292762 Remove .jcheck directories from jdk8u subcomponents
openjdk/jdk8u-dev pull request #110
Opened 2022-08-23 07:29 UTC by gdams

2022-08-26 18:10 UTC, phohensee requested changes
Missed the root directory .jcheck.

2022-08-27 09:31 UTC, gdams commented
@phohensee don’t we need that one? I thought that was used by the skara tooling? It exists in all the other repos

2022-08-28 12:19 UTC, phohensee approved these changes
You're correct. Lgtm.

2022-08-30 17:54 UTC, gdams commented
/intergrate

2022-08-30 17:55 UTC, gdams commented
/integrate

2022-08-30 19:00 UTC, phohensee commented
/sponsor

2022-08-30 19:02 UTC, closed without merging