JDK-8292998: Clean Secmod temporary NSS DB directory before test execution
openjdk/jdk8u-dev pull request #115
Opened 2022-08-26 22:26 UTC by martinuy

Hello,

I'd like to propose this fix as described in https://bugs.openjdk.org/browse/JDK-8292998

The temporary directory used by Secmod tests to copy NSS DB files is deleted (which includes all its files and, potentially, subdirectories) and created empty again. I decided to implement the recursive delete function here for 3 reasons: 1) it's a short and simple function,  2) convenience (we don't have to link every current Secmod test to a test library) and 3) increase chances of backporting future Secmod tests cleanly. Contrary to the approach of setting a minimum jtreg version required, the scope of this change are Secmod tests only and the risk should be minimal.

Thanks,
Martin.-

2022-08-26 22:32 UTC, martinuy commented
/reviewers 1 sgehwolf

2022-08-29 16:17 UTC, jerboaa approved these changes
This looks OK to me. Given that this change makes test runs not leak files from one test to another this is good! Later JDK versions are doing the same, but with a different means. Thumbs up.

2022-08-29 18:06 UTC, zzambers commented
I wander why "DBDIR" is created inside of "classes.dir". Apart from not being cleaned up this also seems like potential source of problems when tests are run concurrently. Couldn't "DBDIR" just be placed in "scratch" [1] directory? Or is there something I am missing here?

[1] https://openjdk.org/jtreg/faq.html#scratch-directory

2022-08-29 20:59 UTC, martinuy commented
Hi @zzambers ,

It's a good point. I think that Secmod tests are not and have never been ready to run in parallel, at least not in 8u. As an example, they copy entire files to the same location without any file system synchronization scheme, which can potentially lead to inconsistencies. What we have fixed here is the sequential run of these tests, which was working before JDK-8195607.

2022-08-31 02:47 UTC, gnu-andrew requested changes

2022-08-31 02:47 UTC, gnu-andrew commented on jdk/test/sun/security/pkcs11/SecmodTest.java
> +    private static void deleteDir(final Path directory) throws IOException {
Can we not use `FileUtils.deleteFileTreeWithRetry(Path)` here? That seems to be the same thing, but with better error handling.

See `jdk/test/lib/jdk/test/lib/util/FileUtils.java`

2022-08-31 02:47 UTC, gnu-andrew commented
/reviewers 2 reviewer

2022-08-31 11:21 UTC, zzambers commented
@martinuy I was just thinking if just turning this line
`DBDIR = System.getProperty("test.classes", ".") + SEP + "tmpdb";`
into
`DBDIR = "." + SEP + "tmpdb";`
instead of doing manual cleanup wouldn't be simpler and more robust solution (using "scratch" dir). But I have not actually tested that...

2022-10-26 20:53 UTC, closed without merging