Backport a41b9a71acdf69b78104677a1ca899ff36293a60
openjdk/jdk8u-dev pull request #186
Opened 2022-11-18 23:48 UTC by lutkerd

Backporting JDK-8229182, did not apply cleanly and had to be manually fixed up.

2022-11-21 21:31 UTC, phohensee requested changes
The copyright line in TestMemoryAwareness and DockerRunOptions.java	 should be

 * Copyright (c) 2017, 2019, Oracle and/or its affiliates. All rights reserved.

This should be backported to 11u before being backport to 8u.

Otherwise, lgtm.

2022-11-22 17:57 UTC, lutkerd commented
> The copyright line in TestMemoryAwareness and DockerRunOptions.java should be
> 
>     * Copyright (c) 2017, 2019, Oracle and/or its affiliates. All rights reserved.

Thanks, fixed!

2022-11-22 18:01 UTC, phohensee approved these changes
Lgtm.

2022-11-23 13:56 UTC, jerboaa commented
This seems fine, but could this wait until after 8u-dev forks to 8u372 (probably next week) and we integrate the cg v2 backports as this conflicts with the patch set?

Note, the work-around seems to be to add `cgroup_enable=memory swapaccount=1` to the kernel command line on the test host.

2022-11-28 17:28 UTC, jerboaa commented
Thanks!

2022-12-06 01:56 UTC, phohensee commented
This PR can now be merged.

2022-12-19 15:55 UTC, jerboaa commented
@lutkerd Feel free to go ahead and integrate. Thanks!

2022-12-27 17:17 UTC, lutkerd commented
/integrate

2022-12-27 20:26 UTC, phohensee commented
/sponsor

2022-12-27 20:28 UTC, closed without merging