Backport 7578044e7107c1914d85894cef5eb712c223252a
openjdk/jdk8u-dev pull request #210
Opened 2022-12-13 09:01 UTC by xiangzhai

Hi,

javax/swing/GroupLayout/7071166/bug7071166.java fail due to TESTBUG.

The patch applies clean except manually change the source file path.

Tested jtreg tier1~3 for fastdebug/release. This backport is only a test change and fixes the test failure.

Thanks,
Leslie Zhai

2022-12-13 15:14 UTC, jerboaa requested changes
One small difference. Once that's fixed it's good to go.

2022-12-13 15:14 UTC, jerboaa commented on jdk/test/javax/swing/JComboBox/6632953/bug6632953.java
> +                    } catch (final UnsupportedLookAndFeelException ignored) {
The JDK 11 patches doesn't have `final` keyword here. Please remove.

2022-12-14 00:47 UTC, xiangzhai commented
Hi @jerboaa 

Thanks for your review!

I updated my patch, please review it again.

Thanks,
Leslie Zhai

2022-12-14 09:53 UTC, jerboaa approved these changes
Looks fine now.

2022-12-14 10:03 UTC, jerboaa commented
/sponsor

2022-12-14 10:05 UTC, closed without merging