Backport 6d83482a6b5f1898514fd450d8143dbfef57e362
openjdk/jdk8u-dev pull request #221
Opened 2023-01-03 12:32 UTC by jmtd

This is a backport of 8293540 to jdk8u-dev for cgroups v2 support.

Unclean: new test (TestDockerBasic.java) needed adjustments for the 8u test library paths and available methods.

2023-01-16 15:11 UTC, jerboaa requested changes
One test related issue, looks good otherwise.

2023-01-19 18:25 UTC, jerboaa commented
@jmtd Please rebase this onto master when you get a chance. Thanks!

2023-01-20 10:48 UTC, jmtd commented
@jerboaa:
> @jmtd Please rebase this onto master when you get a chance. Thanks!

Done :)

2023-01-20 11:10 UTC, jerboaa commented on jdk/test/jdk/internal/platform/cgroup/TestCgroupSubsystemFactory.java
> +        String[] ctrlNames = new String[] { "memory", "cpu", "cpuacct", "blkio", "pids" };
@jmtd This would also need fixing --^ :)

2023-01-23 11:25 UTC, jmtd commented on jdk/test/jdk/internal/platform/cgroup/TestCgroupSubsystemFactory.java
> +        String[] ctrlNames = new String[] { "memory", "cpu", "cpuacct", "blkio", "pids" };
> The pids controller is not present in 8u ([JDK-8266490](https://bugs.openjdk.org/browse/JDK-8266490)). This results in a test failure (NPE). Please remove it.

Thanks for catching. Confirmed, removed, re-tested, pushed.

2023-01-23 13:59 UTC, jerboaa approved these changes
Looks OK now. Thanks.

2023-01-24 10:39 UTC, jmtd commented
/integrate

2023-01-24 10:41 UTC, closed without merging