8305165: [8u] ServiceThread::nmethods_do is not called to keep nmethods from being zombied while in the queue
openjdk/jdk8u-dev pull request #293
Opened 2023-03-29 09:54 UTC by JoshuaZhuwj

Various Crashes in JvmtiExport::post_compiled_method_load were found in
our production environment after users started to receive the JVMTI
COMPILED_METHOD_LOAD event.
ServiceThread::nmethods_do should have been called to keep nmethods from
being zombied while in the JvmtiDeferredEventQueue, but
JavaThead::nmethods_do is called at present.
Make a virtual function call to the correct method to fix this issue.
With the fix, various crashes were gone.
This issue only exists in 8u.

2023-03-30 15:53 UTC, phohensee requested changes
Could you also add 'virtual' to the nmethods_do declaration in JavaThread? Not strictly necessary, but good code hygiene.

2023-03-31 06:56 UTC, JoshuaZhuwj commented
> Could you also add 'virtual' to the nmethods_do declaration in JavaThread? Not strictly necessary, but good code hygiene.

Done. Thanks for your review.

2023-04-03 01:04 UTC, phohensee commented
Also noticed you do not have pre-submit testing enabled. Please do so.

2023-04-04 04:09 UTC, JoshuaZhuwj commented
> Also noticed you do not have pre-submit testing enabled. Please do so.

Done. Thanks for your reminder!

2023-04-04 04:10 UTC, JoshuaZhuwj commented
/integrate

2023-04-25 19:50 UTC, phohensee commented
/sponsor

2023-04-25 19:52 UTC, closed without merging