8235211: serviceability/attach/RemovingUnixDomainSocketTest.java fails with AttachNotSupportedException: Unable to open socket file
openjdk/jdk8u-dev pull request #32
Opened 2022-04-05 00:55 UTC by navyxliu

2022-04-05 01:52 UTC, navyxliu commented
/issue add JDK-8244973

2022-04-05 19:07 UTC, phohensee requested changes
I compared with https://github.com/openjdk/jdk11u-dev/pull/153/.

Lgtm, except there's a missing import in RemovingUnixDomainSocketTest.java and LingeredApp.java, vis

import jdk.test.lib.Utils;

2022-04-06 15:33 UTC, phohensee approved these changes
Lgtm.

2022-05-09 02:57 UTC, gnu-andrew approved these changes
Looks good to me. Clean backport bar the naked_yield/yield change.

2022-05-09 03:00 UTC, gnu-andrew commented
Added `jdk8u-fix-yes`.

2022-05-09 15:55 UTC, navyxliu commented
/integrate

2022-05-09 16:37 UTC, phohensee commented
/sponsor

2022-05-09 16:38 UTC, closed without merging