Backport eccfec498d4062b582282f3b73bba84206a36046
openjdk/jdk8u-dev pull request #337
Opened 2023-07-07 08:43 UTC by sendaoYan

8219804: java/net/MulticastSocket/Promiscuous.java fails intermittently due to NumberFormatException

Reviewed-by: Yi Yang

2023-07-19 02:26 UTC, sendaoYan commented
Please don't close this, bot.

2023-07-19 16:50 UTC, phohensee requested changes
The copyright date update isn't in the original commit, so should be removed. Other than that, looks good. What testing have you done?

2023-07-20 02:59 UTC, sendaoYan commented
> The copyright date update isn't in the original commit, so should be removed. Other than that, looks good. What testing have you done?

mine test command is:
```bash
test=jdk/test/java/net/MulticastSocket/Promiscuous.java
nproc=`nproc` ; dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 1000 | xargs -i -n 1 -P `expr $nproc / 2` bash -c "jtreg -ea -esa -timeoutFactor:4 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```

Before this patch apply, this test intermittently fail:

![image](https://github.com/openjdk/jdk8u-dev/assets/24123821/35181eac-ba43-471b-a067-29a2a183dab7)

After this patch apply, this test run 1000 times all pass:

![image](https://github.com/openjdk/jdk8u-dev/assets/24123821/8da37daa-1662-44e6-b5b3-c6947aab6c0f)

2023-07-20 03:12 UTC, sendaoYan commented
@phohensee The copyright date update has been removed.

2023-07-20 13:32 UTC, phohensee approved these changes
Looks good, thanks for doing the backport.

2023-07-29 10:14 UTC, sendaoYan commented
/integrate

2023-08-02 23:09 UTC, phohensee commented
Tagged the JBS issue.

2023-08-09 16:16 UTC, closed without merging