Backport 992b6c464a9655438a808cf2e1979e04356123be
openjdk/jdk8u-dev pull request #428
Opened 2024-01-25 05:57 UTC by ktakakuri

Hi all, this is a backport of JDK-8159695: Arguments::atojulong() fails to detect overflows.
The bug reported is reproducible in JDK8, so this patch should be applied.
The original patch does not apply cleanly, and the following modifications are needed:

- Lines related to hexadecimal numbers are skipped because support for hexadecimal numbers as a VM option, corresponding to JDK-8042885, was not introduced until JDK9.
- The accompanying test to check the functionality of the atojulong() function is dropped because it is a GTest, which is not available in JDK8.

Note that atomull() was renamed to atojulong() in JDK9 as part of the enhancement JDK-8153073, which supports suffixes in memory size options.
Testing

- Manually check the behaviour
When a given value is too large to fit in a julong, the proper exception is raised with this patch.

without patch
```
java -XX:GCDrainStackTargetSize=999999999999999999999999999999 -XX:+PrintFlagsFinal -version | grep StackTarget

    uintx GCDrainStackTargetSize                   := 18446744073709551615                    {product}
```

with patch
```
java -XX:GCDrainStackTargetSize=999999999999999999999999999999 -XX:+PrintFlagsFinal -version
Improperly specified VM option 'GCDrainStackTargetSize=999999999999999999999999999999'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

- hotspot_tier1

Thank you.

2024-02-29 22:44 UTC, phohensee approved these changes

2024-02-29 22:47 UTC, phohensee requested changes
strtoull is apparently not available or not properly declared for windows-x86.

2024-02-29 23:09 UTC, phohensee approved these changes
windows-x86 GHA build will failure for other reasons (see e.g. https://github.com/openjdk/jdk8u-dev/pull/430), so approving this.

2024-04-16 14:31 UTC, ktakakuri commented
As phohensee has pointed out ,strtoull needs to be declared for Windows-x86. A corresponding fix exists in JDK9, but it's in a different context. I am currently working on backporting this fix in issue #434. Once issue #434 is integrated, the build failure will be resolved and GHA result is fine (see #434).

2024-06-15 17:44 UTC, gnu-andrew commented
I think this one should depend on #434, not the other way around, so VS2010 builds pass.

2024-06-24 01:36 UTC, ktakakuri commented
I think it would be good to merge this backport after #434 is merged.
The fix is no problem as is.

2024-09-03 11:20 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2024-10-02 09:27 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2024-10-31 11:24 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2024-12-03 00:04 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2025-01-06 08:33 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2025-02-12 08:59 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2025-05-20 02:36 UTC, ktakakuri commented
/open

2025-07-15 10:37 UTC, closed without merging