Backport d6a75a0f86d4c84132a3794c432b34068163fa60
openjdk/jdk8u-dev pull request #431
Opened 2024-01-25 11:42 UTC by ktakakuri

Hi all, this is a backport of JDK-8217612: (CL)HSDB cannot show some JVM flags.
The bug reported is reproducible in JDK8, so this patch should be applied.
This patch requires the follow-up patch JDK-8217850 and the correspoding pull request has been submitted.
The original patch does not apply cleanly, and the following modifications are needed:

hotspot/agent/src/share/classes/sun/jvm/hotspot/runtime/VM.java

* Long.toUnsignedString method was introduced in JDK8, and the build fails with JDK7 as the boot-jdk when using this method. Consequently, an alternative private method to Long.toUnsignedString(long i, 10) is required in VM.java.
* The size_t type was introduced in JDK9, so the related fix is skipped.
* To return a String value in the getValue method, the original fix uses a static method, whereas this fix creates a new instance each time. The use of a static method was introduced to JDK-9 in the enhancement JDK-8145061. This enhancement has not been backported, so the same format as the other part of the getValue() method should be used.
* Replace var with String.

2024-04-10 11:44 UTC, ktakakuri commented
Could anyone review this backport please?
Failure of gc/metaspace/CompressedClassSpaceSizeInJmapHeap.java in GHA will be resolved in https://github.com/openjdk/jdk8u-dev/pull/433.

2024-05-21 08:55 UTC, ktakakuri commented
Can someone please review this backport?

2024-06-23 23:44 UTC, ktakakuri commented
Could anyone please review this fix?

2024-08-05 12:45 UTC, ktakakuri commented
Could anyone review this backport please?
Failure of gc/metaspace/CompressedClassSpaceSizeInJmapHeap.java in GHA will be resolved in https://github.com/openjdk/jdk8u-dev/pull/433.

2024-08-05 13:54 UTC, phohensee reviewed
I think we can safely require JDK 8 as the boot JDK. I doubt any JDK 8 developer uses JDK 7 for anything.

2024-08-06 13:11 UTC, ktakakuri commented
In my environment, I am building JDK8 using JDK7 according to the N-1 rule.
As for me, I would like to support builds using JDK7.

2024-08-09 17:21 UTC, phohensee requested changes
I agree with adding ClhsdbFlags.java as a "needed for a future backport", but please add a comment to that effect in place of @test.

2024-08-19 12:09 UTC, ktakakuri commented
I added a comment.

2024-08-19 15:26 UTC, phohensee approved these changes
Thank you.

2024-08-20 06:26 UTC, ktakakuri commented
/approval request This bug is reproducible in JDK8, and backporting this patch is needed. The patch does not apply cleanly due to enhancements introduced since JDK9 and the method that can't be used for building with JDK7. Low risk, tool bug fix. Backport requires follow-up issue JDK-8217850 and the correspoding backport has been submitted.
Tesing: GHA, hotspot_tier1, and manual behaviour checks.

2024-09-18 10:46 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2024-10-17 12:43 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2024-12-16 10:49 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2025-01-14 10:54 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2025-02-12 08:36 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2025-02-12 09:00 UTC, ktakakuri commented
This pull request is pending approval of the Fix Request.
I comment to not close.

2025-05-20 02:30 UTC, ktakakuri commented
/open

2025-05-20 02:32 UTC, ktakakuri commented
/issue add JDK-8217850

2025-07-15 10:37 UTC, closed without merging