MoveToOtherScreenTest fails due wrong key attribute
openjdk/jdk8u-dev pull request #460
Opened 2024-02-27 02:43 UTC by yaqsun

2024-02-27 02:47 UTC, yaqsun commented
/backport jdk8u-dev

2024-02-27 03:11 UTC, theaoqi commented
I think this should not be a backport of [JDK-8164119](https://bugs.openjdk.org/browse/JDK-8164119). May be you should file a new JBS ID for this issue.

2024-02-27 03:49 UTC, yaqsun commented
/approval 8326725 cancel

2024-02-28 05:53 UTC, mrserb approved these changes

2024-02-28 06:06 UTC, yaqsun commented
/approval 8164119 cancel

2024-02-28 12:43 UTC, mrserb requested changes
> I think this should not be a backport of [JDK-8164119](https://bugs.openjdk.org/browse/JDK-8164119). Maybe you should file a new JBS ID for this issue.

You are right.

2024-02-28 12:44 UTC, mrserb approved these changes

2024-02-29 01:42 UTC, yaqsun commented
> ⚠️ @yaqsun This change is now ready for you to apply for [maintainer approval](https://wiki.openjdk.org/display/jdk8u). This can be done directly in each associated issue or by using the [/approval](https://wiki.openjdk.org/display/SKARA/Pull+Request+Commands#PullRequestCommands-/approval) command.

This is a bug, not a backport.
Shouldn't maintainer approval be required?

2024-05-14 03:43 UTC, yaqsun commented
/open

2024-06-11 01:19 UTC, mrserb commented
> > ❗ This change is not yet ready to be integrated. See the **Progress** checklist in the description for automated requirements.
> 
> The **Progress** checklist in the description for automated requirements where can I see it from?
> 
> thanks.

In the description of this PR:
>Progress

>Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
>Change must not contain extraneous whitespace
>Commit message must refer to an issue
[JDK-8326725](https://bugs.openjdk.org/browse/JDK-8326725) needs maintainer approval

right now this PR does not have the "maintainer approval"

2024-06-11 01:42 UTC, yaqsun commented
/approval 8326725 request

2024-06-11 01:43 UTC, yaqsun commented
> right now this PR does not have the "maintainer approval"

Thank you very much for your answer.

2024-06-12 21:06 UTC, mrserb commented
>approval 8326725 request

You should provide the reason for the request and additional details, the list of requirements:
https://openjdk.org/projects/jdk-updates/approval.html

2024-06-13 01:15 UTC, yaqsun commented
/approval 8326725 request Define "headful" jtreg keyword on JDK-8129822, so mark MoveToOtherScreenTest.java as @headful.

2024-08-12 17:33 UTC, mrserb commented
keep open

2024-09-10 00:41 UTC, mrserb commented
keep open

2024-10-16 19:58 UTC, mrserb commented
keep open

2024-11-14 02:28 UTC, yaqsun commented
please take a look

2024-12-12 08:22 UTC, yaqsun commented
keep open

2025-02-06 16:16 UTC, closed without merging

2025-08-28 02:05 UTC, yaqsun commented
keep open