[8u] Unify test libraries into single test library - step 2
openjdk/jdk8u-dev pull request #467
Opened 2024-03-12 15:25 UTC by zzambers

This is second step in the effort to unify duplicate test libraries in jdk8 into single shared test library (as in newer jdks). Motivation is to remove code duplication and make backporting simpler. It only affects tests. More details in [step 1](https://github.com/openjdk/jdk8u-dev/pull/294).

This changeset eliminates duplicate test lib in hotspot ( `hotspot/test/testlibrary` ) by unifying it with shared test library ( `test/lib` ). Hotspot tests have been updated to use (unified) shared test library.

**DETAILS:**
Unification of test libraries was done on per file basis, comparing (diff) classes from both libraries and deciding on approach used. (Generally, files in shared test lib (originally coming from jfr backport) are more updated. However there were some compatibility problems with jdk8 in some places.)

- Legend:
  - kept - kept existing file in shared test library as is
  - same - files in both libraries (hotspot, shared) are effectively same (copyright/package differences etc.) 
  - superset - file in shared test library is superset (in terms of API) of hotspot one

- testlib **packageless** (test/lib)
  - **`ClassFileInstaller.java`** - kept (same)
  - **`RedefineClassHelper.java`**  - used updated one from hs test lib (was missing in shared lib)

- testlib **general** (test/lib/jdk/test/lib)
  - **`Asserts.java`**  - kept (superset)
  - **`BuildHelper.java`**  - kept (same)
  - **`ByteCodeLoader.java`**  - kept (superset)
  - **`JDKToolFinder.java`**  - kept (same)
  - **`JDKToolLauncher.java`**  - kept, with reverted [changes from JDK-8178415](https://github.com/openjdk/jdk11u-dev/commit/05d6891929153c34d101c05a7e04185ebbd05849) to match one from hs test lib (otherwise no real differences)
  - **`Platform.java`** - kept shared version (superset), with some fixes. Updated debug build detection code as jdk8 does not have  `jdk.debug` system property. Removed `areCustomLoadersSupportedForCDS` as this is only useful for appcds tests (not in jdk8)
  - **`Utils.java`**  - kept, added missing `getUnsafe()` method, required by hotspot tests

- testlib **cli** (test/lib/jdk/test/lib/cli)
  - only used by hotspot tests, classes in shared test lib were unused so far
  - used updated files from hotspot test lib, as shared version contained [incompatible changes from JDK-8054892](https://github.com/zzambers/jdk11u-dev/commit/29f7c15af9c8b8199765186c188e9a280f559766) (not backported to jdk8) and did not work with hotspot tests

- testlib **compiler**  (test/lib/jdk/test/lib/compiler)
  - **`InMemoryJavaCompiler.java`**  - used updated one from hs test lib (was missing in shared test lib)

- testlib **conainer** (test/lib/jdk/test/lib/container)
  - **`Common.java`**  - kept (same)
  - **`DockerfileConfig.java`**  - kept (same)
  - **`DockerRunOptions.java`**  - kept, added missing [changes from JDK-8229182](https://github.com/openjdk/jdk8u-dev/commit/c5751e60a8f2a9e5f959b1fbc7fb2d91cd20ece4)
  - **`DockerTestUtils.java`**  - kept, added missing [changes from JDK-8229182](https://github.com/openjdk/jdk8u-dev/commit/c5751e60a8f2a9e5f959b1fbc7fb2d91cd20ece4)

- testlib **management** (test/lib/jdk/test/lib/management)
  -  **`DynamicVMOption.java`**  - kept (same)

- testlib **process** (test/lib/jdk/test/lib/process)
  - **`ExitCode.java`**  - kept (same)
  - **`OutputAnalyzer.java`**  - kept (superset)
  - **`OutputBuffer.java`**  - kept (same)
  - **`ProcessTools.java`** - kept,  with added getPlatformSpecificVMArgs (effectively reverted [changes from JDK-8178415](https://github.com/openjdk/jdk11u-dev/commit/05d6891929153c34d101c05a7e04185ebbd05849)), updated getProcessId (better to throw on error, kept it returning long (as on newer jdks)), removed pid() method from ProcessImpl (not necessary, Process in jdk8 does not have pid method)
  - **`StreamPumper.java`** - kept (superset)

- **whitebox** (test/lib/sun/hotspot)
  - **`Whitebox.java`** - went through differences, removed functions not implemented in hotspot from shared lib. (Also fixed few calls in shared lib, wrongly expecting [changes from JDK-8171008](https://github.com/openjdk/jdk11u-dev/commit/2c220df590f2de212d1fc227b8264cf525be2bcc#diff-e75d116b35afd951f114c2b0793b26d0009b441653d6b28d611afcbe0106dfd0) in jdk8). Result is close to one from hs testlibrary, some wrapper functions around low level functions kept (used in code). 
  - **`Nmethod.java`**  - used updated file from hs test lib, lack of hotspot support (shared lib version expected `wb.getNMethod` to return data in new format - not in jdk8)
  - **`CodeBlob.java`**  - kept, removed getCodeBlobs method (jdk8 hotspot lacks support for WB.getCodeHeapEntries) 
  - **`CPUInfo.java`**  - kept (same)
  - **`DiagnosticCommand.java`**  - used updated file from hs test lib  (jdk8u is missing changes by [JDK-8065783](https://bugs.openjdk.org/browse/JDK-8065783) expected by shared lib version)
  - **`GC.java`**  - removed - unused and (hotspot) support for this is missing in jdk8 (see [JDK-8154096](https://bugs.openjdk.org/browse/JDK-8154096))
  
- testlibrary **other**
  - **`PerfCounter.java`** - moved/updated to `hotspot/test/gc/testlibrary ` [corresponding to newer jdks](https://github.com/openjdk/jdk11u-dev/blob/f3069d13d23301405b096db6d4843500a5f5fa56/test/hotspot/jtreg/gc/testlibrary/PerfCounter.java)
  - **`PerfCounters.java`**  - moved/updated to `hotspot/test/gc/testlibrary` as in newer jdks
  - **`InputArguments.java`**  - moved/updated to `hotspot/test/gc/metaspace` as in newer jdks (see [changes by JDK-8157957](https://github.com/openjdk/jdk11u-dev/commit/ad85e18f236a6771a29156535f68ad4c19feb804#diff-aa68303355ebc129db1b43d89fced9af705509fb570e94743e6e88d48f4a784f))

- **ctw** (compile the world, `hotspot/test/testlibrary/ctw`)
  - ctw was kept in hotspot's testlibrary, as in newer jdks. Makefile was updated, as necessary.
  
- **tests**
  - imports and `@library` tags were fixed, as necessary
  - small fixes to some tests as `ProcessTools.getProcessId()` now returns long (not int). Similar to test modifications [done by JDK-8153992](https://github.com/zzambers/jdk11u-dev/commit/7cf6a15162c794bb200e6e59fc4c81a3cb3cc652) (backport not possible due to ProcessHandle unavailable on jdk8)
  - `hotspot/test/testlibrary_tests/TestMutuallyExclusivePlatformPredicates.java` was updated, as necessary, to work with Platform class from shared test lib

2024-03-12 15:33 UTC, zzambers commented
Test failures in `jdk/tier1` ( `jdk_security_infra` ) are unrelated. They seem to have appeared recently and they also affect newer JDKs, see: [JDK-8324583](https://bugs.openjdk.org/browse/JDK-8324583)
(Newer JDKs just don't run `jdk_security_infra` as part of tier1.)

2024-03-13 15:15 UTC, zzambers commented
Aditional testing:
jdk_jfr: [OK](https://github.com/zzambers/jdk-tester/actions/runs/8263995480/job/22606616559)
jdk_core: [OK](https://github.com/zzambers/jdk-tester/actions/runs/8264016483/job/22610644189) (no regressions to [master](https://github.com/zzambers/jdk-tester/actions/runs/8264248125/job/22607448750); AKISerialNumber.java was [fixed](https://github.com/openjdk/jdk8u-dev/pull/436) in meantime)

2024-03-15 09:55 UTC, sendaoYan commented
AKISerialNumber.java  [fix](https://github.com/openjdk/jdk8u-dev/pull/436) has been merged.

2026-03-25 13:25 UTC, zzambers commented
/open

2026-03-26 11:07 UTC, zzambers commented
/open

2026-03-30 17:09 UTC, zzambers commented
/open

2026-03-31 16:36 UTC, zzambers commented
/open

2026-03-31 16:46 UTC, zzambers commented
Sorry for the noise, I have just discovered, that I cannot force push into branch of closed PR, otherwise it cannot be reopened. See: https://bugs.openjdk.org/browse/SKARA-2700

2026-03-31 16:49 UTC, zzambers commented
I have rebased changes to current master and done some minor (necessary) fixes.
Original PR description holds.

2026-05-11 14:21 UTC, zzambers commented
/touch

2026-05-29 17:38 UTC, gnu-andrew requested changes
Thanks for doing all this review work.  I'd like to finally get this in just after rampdown on 2026-06-05.  You'll need to do `/template append` and tick the AI box to resolve the jcheck issues, and also merge with current 8u-dev.

`Whitebox` is the one that worried me most because the JFR version seemed to bring in a whole bunch of irrelevant stuff, but it looks like you've resolved that.  Given the size of this change, I'd like to get this in so people can try it out and find any issues. I think that works better than trying to comb through every change to 479 files.

2026-06-01 08:41 UTC, zzambers commented
/template append

2026-06-01 09:15 UTC, zzambers commented
> Thanks for doing all this review work. I'd like to finally get this in just after rampdown on 2026-06-05. You'll need to do `/template append` and tick the AI box to resolve the jcheck issues, and also merge with current 8u-dev.
> 
> `Whitebox` is the one that worried me most because the JFR version seemed to bring in a whole bunch of irrelevant stuff, but it looks like you've resolved that.

Yes, I believe `Whitebox` should be good, I analyzed differences on per-file basis and decided on changes based on that (irrelevant stuff should be removed) + tests look good.

> Given the size of this change, I'd like to get this in so people can try it out and find any issues. I think that works better than trying to comb through every change to 479 files.

Thank you for looking into this. I know it is a huge changeset.. :(

2026-06-30 09:24 UTC, zzambers commented
/touch

2026-07-23 20:48 UTC, gnu-andrew commented
Still needs a merge with the latest 8u-dev so we can get a fresh test run.

2026-08-24 10:08 UTC, zzambers commented
/touch

2026-08-24 10:25 UTC, zzambers commented
merged master

2026-08-24 12:22 UTC, zzambers commented
Tests look OK. Failures seem unrelated (jdk_security_infra + 1 jdk/tier1 on Mac with "network unreachable").

2026-09-18 17:32 UTC, gnu-andrew commented
@zzambers test results looked ok.  Another merge should do it.

2026-09-21 14:09 UTC, zzambers commented
Merged, there was one conflicting change set:
https://github.com/openjdk/jdk8u-dev/commit/b7263cc392fab54d33741094407b9a2a24720a8d

Just manually applied changes to WhiteBox.java in unified location.

2026-09-21 18:30 UTC, gnu-andrew approved these changes
Still looks good.  GHA as usual for 8u.  Let's get this in.

2026-09-22 10:19 UTC, zzambers commented
/approval request Unifies test libraries to limit code duplicity and to make structure more similar to newer jdks, it affects test code only, testing in GHA ok.

2026-09-22 22:06 UTC, gnu-andrew commented
/approve yes

2026-09-22 23:50 UTC, zzambers commented
/integrate

2026-09-22 23:54 UTC, closed without merging