Backport 1b925183894778acce8aff4c101f67af98f0097f
openjdk/jdk8u-dev pull request #476
Opened 2024-04-01 10:21 UTC by psawant19

Backporting JDK-8235834 - IBM-943 charset encoder needs updating.
There are few characters which display garbled values when using IBM943C, so this mapping file needs to be backported to fix the issue.

Reported issue : https://bugs.openjdk.org/browse/JDK-8235834

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Error
&nbsp;⚠️ OCA signatory status must be verified

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/476/head:pull/476` \
`$ git checkout pull/476`

Update a local copy of the PR: \
`$ git checkout pull/476` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/476/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 476`

View PR using the GUI difftool: \
`$ git pr show -t 476`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/476.diff">https://git.openjdk.org/jdk8u-dev/pull/476.diff</a>

</details>

2024-04-01 10:22 UTC, psawant19 commented
This contribution is on behalf of my employer, IBM, which is a corporate OCA signatory.

2024-04-01 10:22 UTC, psawant19 commented
/covered

2024-04-02 06:14 UTC, psawant19 commented
/covered

2024-04-08 04:23 UTC, psawant19 commented
/covered

2024-04-15 09:55 UTC, psawant19 commented
Closing this PR as my OCA verification is taking too long to approve. 
Opened another PR by a different contributor:- https://github.com/openjdk/jdk8u-dev/pull/480.

2024-04-29 04:31 UTC, psawant19 commented
/covered

2024-04-29 04:38 UTC, psawant19 commented
Backporting JDK-8235834 - IBM-943 charset encoder needs updating.
There are few characters which display garbled values when using IBM943C, so this mapping file needs to be backported to fix the issue.

Reported issue : https://bugs.openjdk.org/browse/JDK-8235834.

2024-04-29 04:48 UTC, psawant19 commented
@gnu-andrew, @mrserb Could you please review this PR.

2024-05-03 13:35 UTC, offamitkumar commented
Hi @psawant19 , 
This PR doesn't make any sense if https://github.com/openjdk/jdk8u-dev/pull/480 is in review. Please close one of them.

2024-05-06 04:52 UTC, offamitkumar commented on jdk/test/sun/nio/cs/TestIBMBugs.java
> + * @modules jdk.charsets
Please make sure that you're only backporting the "changes" done by the head-stream patch. Not more than that (if not required). See my comments on #480 .

2024-05-06 11:41 UTC, psawant19 commented
/clean The patch is identical to the patch in jdk11u-dev.

2024-05-13 06:30 UTC, offamitkumar commented
Please merge master branch and that should trigger the GHA test again.

2024-05-13 11:34 UTC, offamitkumar commented
>/integrate

@psawant19, Please go through the contribution guidelines. Don't just integrate!!

There is progress check list on your PR. Once all of them are marked as `completed`. Then only you should go for integration. 

So for now, You need: 
1.  approval from **R**ivewer. 
2. approval from Maintainer.

>Failures are a Certigna certificate test and an Ubuntu packages not available at specified path. Hence integrating.

I asked you to merge master branch in `psawant19:IBM943-support-backport-1b9251` so that Github will run the test cases again. Please do it!!

2024-05-15 11:01 UTC, offamitkumar commented
I guess something went wrong with GHA test. Have you turned off Github Actions ? 

@RealCLanger is it possible to get review from you ?

2024-05-15 12:51 UTC, jerboaa requested changes
The test fails:

```
/disk/openjdk/upstream-sources/git/jdk8u-dev/jdk/test/sun/nio/cs/TestIBMBugs.java:223: error: cannot find symbol
            if (!Arrays.equals(byteIBM943c2b, strIBM943c2b1.getBytes(cs))) {
                 ^
  symbol:   variable Arrays
  location: class TestIBMBugs
1 error
result: Failed. Compilation failed: Compilation failed
```

Adding the import should fix it.

Also, please enable GHA for your fork and show some evidence on what testing you've done for this. Thanks!

2024-05-16 07:41 UTC, psawant19 commented
@jerboaa,
I have fixed the compilation error and GHAs are enabled on this repo.
IBM943 mapping document link: https://www.fileformat.info/info/charset/x-IBM943/list.htm

Attaching test evidences for the bug fix with before and after screenshots.

Before fix:
<img width="1384" alt="image" src="https://github.com/openjdk/jdk8u-dev/assets/30701198/8773d3a1-a185-4806-9b7e-b585cddfb5da">

After fix:
<img width="1384" alt="image" src="https://github.com/openjdk/jdk8u-dev/assets/30701198/f4d99e66-16bf-41b4-b665-365f8301b26a">

2024-05-16 08:38 UTC, jerboaa commented
@psawant19 Thanks. Please also show that the `sun/nio/cs` jtreg tests are passing.

2024-05-16 08:40 UTC, jerboaa approved these changes
This looks OK.

2024-05-16 08:40 UTC, jerboaa commented
> I have fixed the compilation error and GHAs are enabled on this repo.

Please merge lastest master into your branch, which should make the certinga CA tests failure go away.

2024-05-16 11:07 UTC, psawant19 commented
@jerboaa,
There is still 1 pre-test failing that is because these below packages doesn't exist at this location. 
- https://httpredir.debian.org/debian/dists/buster/main/binary-s390x/Packages
- https://httpredir.debian.org/debian/dists/buster/main/binary-ppc64el/Packages

Is the PR good to go for maintainer approval?

2024-05-16 11:13 UTC, offamitkumar commented
>Is the PR good to go for maintainer approval?


Yes, use `/approval request <your reason>` to apply for the approval. Please give justification why you want to backport the changes, what testing you have done and what is risk (low/high). In this case it should be low.

2024-05-16 11:24 UTC, psawant19 commented
/approval request This back port is required to display Japanese locale which uses IBM943 charset. The fix is tested in a linux environment and the test case passes as mentioned in the screenshot above.

2024-05-16 11:55 UTC, jerboaa commented
The follow-up, [JDK-8239965](https://bugs.openjdk.org/browse/JDK-8239965), needs backporting too. Please do that so that I can approve them as a unit.

2024-05-16 12:59 UTC, psawant19 commented
This is the PR (https://github.com/openjdk/jdk8u-dev/pull/500) created for backporting [JDK-8239965](https://bugs.openjdk.org/browse/JDK-8239965).

2024-05-17 13:08 UTC, psawant19 commented
/integrate

2024-05-22 12:23 UTC, jerboaa commented
/sponsor

2024-05-22 12:24 UTC, closed without merging