8335552: [8u] JDK-8303466 backport to 8u requires 3 ::Identity signature fixes
openjdk/jdk8u-dev pull request #532
Opened 2024-07-02 14:23 UTC by franferrax

Hi, here is a followup fix for #529, where @wkia has noted a problem with the `MaxLNode::Identity`, `MinLNode::Identity` and `ConvI2LNode::Identity` signatures: https://github.com/openjdk/jdk8u-dev/pull/529#discussion_r1661486052.

2024-07-02 22:15 UTC, martinuy approved these changes
Looks good to me.

2024-07-03 07:08 UTC, rwestrel approved these changes
Looks good to me.

2024-07-03 08:50 UTC, jerboaa commented
@franferrax Please apply for approval of this bug, thanks!

2024-07-03 12:11 UTC, franferrax commented
/approval request jdk8u is affected by this bug after the JDK-8335472 integration. ::Identity methods are not being invoked, leading to sub-optimal code for MaxLNode, MinLNode and ConvI2LNode. The patch has been reviewed and GitHub Actions passed (except for macOS, where the jobs are still waiting for an available runner to pick them).

2024-07-03 13:59 UTC, franferrax commented
I just noticed that, given cbd483afa413f006c991f1b4d92c83463cc11baa, this is a clean backport of JDK 9's [JDK-8075511](https://bugs.openjdk.org/browse/JDK-8075511 "Enable -Woverloaded-virtual C++ warning for HotSpot build") (openjdk/jdk9u@8efb3ab7c1cf0164237c50d60c4cd564b3d6a897). For the sake of clarity, I will add the issue and apply for approval there too. Sorry @jerboaa for bothering you with one more approval.

2024-07-03 14:00 UTC, franferrax commented
/issue add 8075511

2024-07-03 14:07 UTC, franferrax commented
/approval 8075511 request JDK-8335552 could have been avoided with this warning (treated as error in GitHub Actions). A 8u backport is already part of the approved PR.

2024-07-03 14:13 UTC, jerboaa commented
> I just noticed that, given [cbd483a](https://github.com/openjdk/jdk8u-dev/commit/cbd483afa413f006c991f1b4d92c83463cc11baa), this is a clean backport of JDK 9's [JDK-8075511](https://bugs.openjdk.org/browse/JDK-8075511) ([openjdk/jdk9u@8efb3ab](https://github.com/openjdk/jdk9u/commit/8efb3ab7c1cf0164237c50d60c4cd564b3d6a897)). For the sake of clarity, I will add the issue and apply for approval there too. Sorry @jerboaa for bothering you with one more approval.

@franferrax Hmm, thinking some more about this and seeing the warnings on the added issue. Please create a separate backport for it and then merge that into this one.

2024-07-03 14:27 UTC, franferrax commented
/issue add 8335552

2024-07-03 14:34 UTC, gnu-andrew requested changes
Yes, please separate the enhancement into a separate PR. Adding a new warning has a different potential impact to just fixing the bug introduced by JDK-8335472

2024-07-03 14:35 UTC, gnu-andrew commented
/reviewers 3 reviewer

2024-07-03 14:51 UTC, franferrax commented
@jerboaa:
> @franferrax Hmm, thinking some more about this and seeing the warnings on the added issue. Please create a separate backport for it and then merge that into this one.

How about it now? The PR is recognized as a backport, links both issues and has the title of the most relevant one.

-----

@gnu-andrew:
> Yes, please separate the enhancement into a separate PR. Adding a new warning has a different potential impact to just fixing the bug introduced by JDK-8335472

@jerboaa was referring to the Skara tooling warning saying that the PR wasn't being recognized as a backport. With respecto to the GCC warning, it would have prevented [JDK-8335472](https://bugs.openjdk.org/browse/JDK-8335472 "C2: failed: malformed control flow. Limit type made precise with MaxL/MinL"). The addition of the warning has been there since the beginning of the PR, which has been reviewed and approved with that change.

What happened, is that later I realized that the change is in fact a clean backport of [JDK-8075511](https://bugs.openjdk.org/browse/JDK-8075511 "Enable -Woverloaded-virtual C++ warning for HotSpot build") and wanted to document that fact.

-----

@jerboaa, @gnu-andrew: are you OK to continue in this way?

2024-07-03 15:36 UTC, gnu-andrew commented
> @jerboaa:
> 
> > @franferrax Hmm, thinking some more about this and seeing the warnings on the added issue. Please create a separate backport for it and then merge that into this one.
> 
> How about it now? The PR is recognized as a backport, links both issues and has the title of the most relevant one.
> 
> @gnu-andrew:
> 
> > Yes, please separate the enhancement into a separate PR. Adding a new warning has a different potential impact to just fixing the bug introduced by JDK-8335472
> 
> @jerboaa was referring to the Skara tooling warning saying that the PR wasn't being recognized as a backport. With respecto to the GCC warning, it would have prevented [JDK-8335472](https://bugs.openjdk.org/browse/JDK-8335472). The addition of the warning has been there since the beginning of the PR, which has been reviewed and approved with that change.
> 
> What happened, is that later I realized that the change is in fact a clean backport of [JDK-8075511](https://bugs.openjdk.org/browse/JDK-8075511) and wanted to document that.
> 
> @jerboaa, @gnu-andrew: are you OK to continue in this way?

No. Please make [JDK-8075511](https://bugs.openjdk.org/browse/JDK-8075511) a separate PR and commit. I agree it is good to catch these kind of failures in future, but it is not a pre-requisite for fixing this bug. 8u is built on a wide range of compilers and isolating the warning change to an individual fix makes it easier to deal with any impact.

2024-07-03 15:39 UTC, franferrax commented
@gnu-andrew: ok, sounds reasonable, no problem!

2024-07-03 15:41 UTC, gnu-andrew commented
> @gnu-andrew: ok, sounds reasonable, no problem!

Thanks for your understanding. You should just be able to backout the commit from this PR and drop the bug ID.

2024-07-03 16:03 UTC, franferrax commented
/issue remove 8075511

2024-07-03 16:06 UTC, franferrax commented
/label remove backport

2024-07-03 16:19 UTC, franferrax commented
/backport disable jdk8u-dev

2024-07-03 17:27 UTC, franferrax commented
@gnu-andrew: the only thing I could not do is to remove the `backport` label from this PR. I suspect that [`/label remove backport`](https://github.com/openjdk/jdk8u-dev/pull/532#issuecomment-2206706608) would have worked if issued by someone with enough privileges.

2024-07-03 21:18 UTC, gnu-andrew approved these changes
Patch looks fine now. Let's see what the commit message says to see if the backport label is an issue.

2024-07-03 22:32 UTC, gnu-andrew commented
> Patch looks fine now. Let's see what the commit message says to see if the backport label is an issue.

Doesn't look to be.

2024-07-03 23:33 UTC, franferrax commented
/integrate

2024-07-03 23:35 UTC, martinuy commented
/sponsor

2024-07-03 23:36 UTC, closed without merging

2024-07-03 23:42 UTC, franferrax commented
@gnu-andrew
> > Patch looks fine now. Let's see what the commit message says to see if the backport label is an issue.
> 
> Doesn't look to be.

Hmmm, but the final commit message still included `Backport-of: 8efb3ab7c1cf0164237c50d60c4cd564b3d6a897`.

2024-07-04 02:04 UTC, gnu-andrew commented
> @gnu-andrew
> 
> > > Patch looks fine now. Let's see what the commit message says to see if the backport label is an issue.
> > 
> > 
> > Doesn't look to be.
> 
> Hmmm, but the final commit message still included `Backport-of: 8efb3ab7c1cf0164237c50d60c4cd564b3d6a897`.

Ugh. I don't see a way we could have removed it and this wasn't in the preview commit summary. Might be worth a SKARA bug.

2024-07-04 13:32 UTC, franferrax commented
The original backport hash [is obtained](https://github.com/openjdk/skara/blob/273c362ab262134584830fc99adfd23f6f7ee0f7/bots/pr/src/main/java/org/openjdk/skara/bots/pr/CheckablePullRequest.java#L322-L333) from a hidden comment in [this message](https://github.com/openjdk/jdk8u-dev/pull/532#issuecomment-2206284623) with a [specific format](https://github.com/openjdk/skara/blob/273c362ab262134584830fc99adfd23f6f7ee0f7/bots/pr/src/main/java/org/openjdk/skara/bots/pr/CheckablePullRequest.java#L43) (we can see the hidden part in the [raw message body](https://api.github.com/repos/openjdk/jdk8u-dev/issues/comments/2206284623)).

The `/integrate` command then [passes this backport hash as `original`](https://github.com/openjdk/skara/blob/273c362ab262134584830fc99adfd23f6f7ee0f7/bots/pr/src/main/java/org/openjdk/skara/bots/pr/IntegrateCommand.java#L218-L226) when creating the commit and, [unlike the `/clean` command](https://github.com/openjdk/skara/blob/273c362ab262134584830fc99adfd23f6f7ee0f7/bots/pr/src/main/java/org/openjdk/skara/bots/pr/CleanCommand.java#L66), the `backport` label isn't checked. The commit message's `original` [finally ends up in the `Backport-of:` footer](https://github.com/openjdk/skara/blob/273c362ab262134584830fc99adfd23f6f7ee0f7/vcs/src/main/java/org/openjdk/skara/vcs/openjdk/CommitMessageFormatters.java#L94).

So even if we managed to remove the `backport` label, the `Backport-of:` footer would still have been generated, as long as [this message](https://github.com/openjdk/jdk8u-dev/pull/532#issuecomment-2206284623) is readable by the bot.

Apparently, a PR that starts or becomes a backport, is totally unexpected to return to a non-backport state. Knowing about this irreversible process is enough for me, to be more careful next time. In the unlikely case we need to return to a non-backport PR in the future, we can just start a new PR.