Backport c1bb926f4d5eaf49777f93b9f8788db243bba83b
openjdk/jdk8u-dev pull request #538
Opened 2024-07-08 06:58 UTC by sendaoYan

Hi all
This is backport of JDK-8309138, to fix the testcase bug, which if the tested jdk directory is symlinked, symlinks are followed when copying tested jdk.
Only change the testcase lib file, the risk is low.

Additional testing:

- [ ] jdk/test/jdk/internal/platform/docker
- [ ] hotspot/test/runtime/containers/docker

2024-07-08 07:18 UTC, sendaoYan commented
/request Backport of JDK-8309138 to fix the testcase bug, which if the tested jdk directory is symlinked, symlinks are followed when copying tested jdk. Only change the testcase lib file, the risk is low.

2024-07-08 07:24 UTC, sendaoYan commented
/approval request Backport of JDK-8309138 to fix the testcase bug, which if the tested jdk directory is symlinked, symlinks are followed when copying tested jdk. Only change the testcase lib file, the risk is low.

2024-07-08 08:03 UTC, sendaoYan commented
The GHA test runner report several failures, all the failures are CA issues, which is fixing by [pr526](https://github.com/openjdk/jdk8u-dev/pull/526) now. It's unrelated to this PR.

```
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#digicerttlseccrootg5
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#digicerttlsrsarootg5
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#quovadisrootca1g3
```

2024-07-26 20:20 UTC, phohensee approved these changes

2024-07-27 01:08 UTC, sendaoYan commented
Thanks for the review.

2024-08-20 15:34 UTC, jerboaa requested changes
Please include the same change in the Hotspot copy of `DockerTestUtils.java` in this backport.

2024-08-20 15:35 UTC, sendaoYan commented
> Please include the same change in the Hotspot copy of `DockerTestUtils.java` in this backport.

Okey.

2024-08-20 15:49 UTC, sendaoYan commented
> Please include the same change in the Hotspot copy of `DockerTestUtils.java` in this backport.

Thanks for the advice. The Hotspot copy of `DockerTestUtils.java` has included the same change just now.

2024-08-20 15:59 UTC, phohensee approved these changes

2024-08-20 16:01 UTC, jerboaa approved these changes
LGTM.

2024-08-20 16:14 UTC, sendaoYan commented
/approval request Backport of JDK-8309138 to fix the testcase bug, which if the tested jdk directory is symlinked, symlinks are followed when copying tested jdk. Only change the testcase lib file, the risk is low.

2024-08-21 01:03 UTC, sendaoYan commented
Thanks all for the review and approved.
/integrate

2024-08-21 08:46 UTC, jerboaa commented
/sponsor

2024-08-21 08:47 UTC, closed without merging

2024-08-21 09:08 UTC, sendaoYan commented
Thanks for the sponsor.