8u backport of JDK-8049228
openjdk/jdk8u-dev pull request #70
Opened 2022-06-01 03:41 UTC by lusou-zhangquan

8049228: Improve multithreaded scalability of InetAddress cache
7186258: InetAddress$Cache should replace currentTimeMillis with nanoTime for more precise and accurate

Backport-of 250fbb065a789a303d692d698c9b69117bf6cd2c

2022-06-20 13:47 UTC, jerboaa commented
> @jerboaa PR title has been changed as your advise, but I have no idea about how to close the manual bug JDK-8288718 I created. Could you please provide any suggestions?

I've closed it as a duplicate for you now.

2022-06-21 06:48 UTC, lusou-zhangquan commented
> > @jerboaa PR title has been changed as your advise, but I have no idea about how to close the manual bug JDK-8288718 I created. Could you please provide any suggestions?
> 
> I've closed it as a duplicate for you now.

Thanks a lot. Won't make similar mistakes next time.

2022-06-21 06:50 UTC, lusou-zhangquan commented
> Looks fine, but please run at least tier1 tests.

Re-run the gate and passed. Please take a look again.

2022-07-18 09:26 UTC, lusou-zhangquan commented
@phohensee Please take a look at this PR again, thanks a lot.

2022-07-18 18:48 UTC, phohensee approved these changes
Lgtm.

2022-07-19 01:55 UTC, lusou-zhangquan commented
/integrate

2022-07-19 08:28 UTC, jerboaa commented
@lusou-zhangquan Please only issue /integrate once you have `jdk8u-fix-yes` on the bug. See "Contributing" section in https://wiki.openjdk.org/display/jdk8u In particular steps 10 and 11.

2022-07-27 02:39 UTC, lusou-zhangquan commented
> @lusou-zhangquan Please only issue /integrate once you have `jdk8u-fix-yes` on the bug. See "Contributing" section in https://wiki.openjdk.org/display/jdk8u In particular steps 10 and 11.

Sorry for not following the contributing rules. The latest comment of this bug mentions this PR but no `jdk8u-fix-yes` label attached. Should I keep waiting or request for maintainer's review to let it move on? Will appreciate if you could give any advice.

2022-07-27 15:36 UTC, phohensee commented
lusou-zhangquan, I've tagged both issues with jdk8u-fix-request on your behalf. If you post here any additional justification you may have, I'll add it to the fix request comment.

2022-07-28 02:23 UTC, lusou-zhangquan commented
> lusou-zhangquan, I've tagged both issues with jdk8u-fix-request on your behalf. If you post here any additional justification you may have, I'll add it to the fix request comment.

Thanks a lot for your help.

2022-08-15 08:43 UTC, gnu-andrew approved these changes
Looks like a clean backport, bar the copyright header that has already been updated by later security changes.

2022-08-15 09:01 UTC, gnu-andrew commented
I've approved this one, but as I commented on the bug, it would be nice to know the reasoning for this backport. Approvals are primarily about risk assessment in the context of the whole JDK.

In this case, it's been in later JDKs for years, and is realistically borderline between being an enhancement and a bug fix (see https://bugs.openjdk.org/browse/JDK-8171346). I think it would be preferable to deal with any issues in the new code rather than the current outdated code, which is doing its own locking that is prone to error.

2022-08-15 19:23 UTC, phohensee commented
@ lusou-zhangquan, I strongly suspect the copyright date conflict in InetAddressCachePolicy.java would cause a merge failure if I sponsored this. Once you fix it I'll re-review and sponsor.

2022-08-16 02:40 UTC, lusou-zhangquan commented
> I've approved this one, but as I commented on the bug, it would be nice to know the reasoning for this backport. Approvals are primarily about risk assessment in the context of the whole JDK.
> 
> In this case, it's been in later JDKs for years, and is realistically borderline between being an enhancement and a bug fix (see https://bugs.openjdk.org/browse/JDK-8171346). I think it would be preferable to deal with any issues in the new code rather than the current outdated code, which is doing its own locking that is prone to error.

This bug is reproduced in our DNS service, which is running on jdk8 and hard to be upgraded to newer versions. So we hope to backport it and eliminate this risks for all jdk8 users.

2022-08-16 05:47 UTC, lusou-zhangquan commented
> @ lusou-zhangquan, I strongly suspect the copyright date conflict in InetAddressCachePolicy.java would cause a merge failure if I sponsored this. Once you fix it I'll re-review and sponsor.

Copyright date has been updated in latest commit, thanks for your suggestion.

2022-08-16 21:22 UTC, gnu-andrew requested changes
Wait, what? Why are we changing the copyright dates? This is not part of the original patch. Please revert this change.

2022-08-16 21:25 UTC, gnu-andrew commented
/reviewers 2 reviewer

2022-08-21 17:52 UTC, phohensee commented
That was my bad. Somehow I thought the original patch updated the copyright date. Please revert to the previous version.

2022-08-22 19:34 UTC, gnu-andrew commented
> That was my bad. Somehow I thought the original patch updated the copyright date. Please revert to the previous version.

No worries. I just couldn't work out the issue you were referring to and indeed there is no 2022 bump in the original patch.

2022-08-22 19:35 UTC, gnu-andrew approved these changes
Ok, let's try again :)

2022-08-23 13:42 UTC, phohensee commented
Just need an integrate comment. :)

2022-08-24 02:15 UTC, lusou-zhangquan commented
/summary
8049228: Improve multithreaded scalability of InetAddress cache
7186258: InetAddress$Cache should replace currentTimeMillis with nanoTime for more precise and accurate

Reviewed-by: phh, andrew

2022-08-24 02:19 UTC, lusou-zhangquan commented
/summary

2022-08-24 02:37 UTC, lusou-zhangquan commented
> /summary 8049228: Improve multithreaded scalability of InetAddress cache 7186258: InetAddress$Cache should replace currentTimeMillis with nanoTime for more precise and accurate
> 
> Reviewed-by: phh, andrew

I intended to update summary of this PR with this `summary` command before integrate, but it looks like not working as expected. And now jcheck failed with this error message:
```
Exception occurred during jcheck - the operation will be retried

Incorrectly formatted commit message: 8049228: Improve multithreaded scalability of InetAddress cache
7186258: InetAddress$Cache should replace currentTimeMillis with nanoTime for more precise and accurate

8049228: Improve multithreaded scalability of InetAddress cache
7186258: InetAddress$Cache should replace currentTimeMillis with nanoTime for more precise and accurate

Reviewed-by: phh, andrew

Reviewed-by: phh, Andrew
```
Is this my operation fault or jcheck bug? Could anybody help to solve this problem. Thanks a lot.

2022-08-24 12:19 UTC, jerboaa commented
> > /summary 8049228: Improve multithreaded scalability of InetAddress cache 7186258: InetAddress$Cache should replace currentTimeMillis with nanoTime for more precise and accurate
> > Reviewed-by: phh, andrew
> 
> I intended to update summary of this PR with this `summary` command before integrate, but it looks like not working as expected. And now jcheck failed with this error message:
> 
> ```
> Exception occurred during jcheck - the operation will be retried
> 
> Incorrectly formatted commit message: 8049228: Improve multithreaded scalability of InetAddress cache
> 7186258: InetAddress$Cache should replace currentTimeMillis with nanoTime for more precise and accurate
> 
> 8049228: Improve multithreaded scalability of InetAddress cache
> 7186258: InetAddress$Cache should replace currentTimeMillis with nanoTime for more precise and accurate
> 
> Reviewed-by: phh, andrew
> 
> Reviewed-by: phh, Andrew
> ```
> 
> Is this my operation fault or jcheck bug? Could anybody help to solve this problem. Thanks a lot.

Don't set the commit message like that using `/summary`. What you want is `/issue add`. `Reviewed-by` fields are set by the bots based on the approving reviewers, so it's no surprise it didn't like that. That being said, for all intents an purposes what the bot suggested in https://github.com/openjdk/jdk8u-dev/pull/70#issuecomment-1188121988 pretty much matches what you want, no? What is it that you want to achieve exactly?

2022-08-24 12:22 UTC, jerboaa commented
/summary
Remove me

2022-08-24 12:26 UTC, jerboaa commented
@lusou-zhangquan It looks like that has broken the bots. Best to file a SKARA issue here: https://bugs.openjdk.org/browse/SKARA if you can't create issues, I can help with that.

2022-08-24 17:49 UTC, gnu-andrew commented
It's probably simpler to just open a fresh PR.

2022-08-25 02:30 UTC, lusou-zhangquan commented
Close this PR and open a fresh one because of broken bots.

2022-08-25 02:30 UTC, closed without merging