Backport b8ab854bdcf625772e965a5e476e0a9db1b91f3f
openjdk/jdk8u-dev pull request #77
Opened 2022-06-22 08:31 UTC by apavlyutkin

Hi! Please review another backport from MSVS2019 seria. This one fixes type declarations made by globalDefinitions_VisCPP.hpp. The patch from 11u applied with the following changes:

- inttypes.h is included conditionally under `_MSC_VER >= 1800` because the header was introduced only in MSVS 2013 but we have to keep support of the earlier MSVS versions 
- the duplicates of declarations made in inttypes.h are not just removed but quoted with `_MSC_VER < 1800`
- common\autoconf\generated-configure.sh is regenerated to add MSVS2019 recognition (I forgot to do that in https://github.com/openjdk/jdk8u-dev/pull/33)

Verification: 2019 build (both 32/64) now fails with 
```
ad_x86_64_pipeline.obj : error LNK2011: precompiled object not linked in; image may not run
jvm.dll : fatal error LNK1120: 1 unresolved externals
```
error (to be fixed by backport of 8043492)

Regression: 2017/2013/2012/2010 full build - ok

@kimbarrett @dholmes-ora if you took a look at that it would be very much appreciated

2022-07-19 06:16 UTC, apavlyutkin commented
ping

2022-08-02 06:18 UTC, apavlyutkin commented
Guys, this one stops a seria of backports required to support VS 2019/22. Could somebody to review it? Thank you

2022-08-22 04:36 UTC, apavlyutkin commented
ping

2022-09-01 06:12 UTC, apavlyutkin commented
ping

2022-09-01 08:49 UTC, jerboaa requested changes
Why is `generated-configure.sh` part of this change? It doesn't touch m4 scripts.

2022-09-01 08:53 UTC, jerboaa commented
> Why is `generated-configure.sh` part of this change? It doesn't touch m4 scripts.

Ah, you mentioned it in the description. Forgotten in https://github.com/openjdk/jdk8u-dev/pull/33. Either way, this shouldn't be part of this backport. It's unrelated and just confuses people when looking at the backport after the fact. Please open and 8u-specific bug and correct this. Also, it's not clear why `generated-configure.sh` would be this large. Are you generating it with the right system? If you do it on a wrong one it can get messy and mixes unrelated changes due to version skew.

2022-09-02 07:05 UTC, apavlyutkin commented
Ok, I removed generated-configure.sh from the PR, probably the best option here to commit it after the rest of VS2019 backports (there are 2-3 more) are done

2022-09-15 19:32 UTC, apavlyutkin commented
ping

2022-10-21 14:35 UTC, jerboaa reviewed
It would be good if some Windows build person could review this patch as well.

2022-10-21 14:35 UTC, jerboaa commented on hotspot/src/share/vm/utilities/globalDefinitions_visCPP.hpp
> -#endif
These removals aren't in the original changeset. See JDK-8272714 and JDK-8272214. I guess we should conditionalize on the VS version in use if that's a problem?

2022-10-21 16:56 UTC, apavlyutkin commented
The definitions now are done by including of `stdint.h` that is surely available even in msvs 2010 (as I remember a far earlier). I have no idea why they were declared localy. Looks like I forgot to mention this deviation from the original changeset.

2022-10-22 06:21 UTC, apavlyutkin commented
/label add build

2022-10-23 10:16 UTC, apavlyutkin commented
/cc build-dev@openjdk.org

2022-10-25 13:22 UTC, jerboaa commented
> The definitions now are done by including of `stdint.h` that is surely available even in msvs 2010 (as I remember a far earlier). I have no idea why they were declared localy. Looks like I forgot to mention this deviation from the original changeset.

OK, thanks.

2022-10-31 12:29 UTC, apavlyutkin commented
> > The definitions now are done by including of `stdint.h` that is surely available even in msvs 2010 (as I remember a far earlier). I have no idea why they were declared localy. Looks like I forgot to mention this deviation from the original changeset.
> 
> OK, thanks.

Luckily the guys from my old job still use msvs-2008. I asked them to check presense of `stdint.h`, and the header was introduced exactly in msvs-2010. Looks like jdk-8 didn't use the header to provide compatibility with the compilers older than 2010, but now it does not make a sense

2022-11-16 18:20 UTC, phohensee requested changes
The copyright date should stay at 2018 because that's what the original commit had. Other than that, lgtm.

2022-11-16 18:33 UTC, apavlyutkin commented
> The copyright date should stay at 2018 because that's what the original commit had. Other than that, lgtm.

fixed

2022-11-16 19:23 UTC, phohensee approved these changes
Thanks, lgtm.

2022-11-16 19:39 UTC, apavlyutkin commented
Thank you for the review

2022-11-17 08:56 UTC, apavlyutkin commented
/integrate

2022-11-17 09:00 UTC, yan-too commented
/sponsor

2022-11-17 09:01 UTC, closed without merging