Backport 70762d397267f85ce81727ec0c89c9448967798e
openjdk/jdk8u-dev pull request #81
Opened 2022-06-28 05:53 UTC by mrserb

...placeholder...

2022-06-28 16:47 UTC, phohensee approved these changes
Lgtm.

2022-08-03 20:13 UTC, mrserb commented
/issue add 8288928

2022-08-31 02:23 UTC, gnu-andrew requested changes
Backport looks good
8u-dev is currently closed for rampdown so please wait until it reopens before integrating.

2022-08-31 02:23 UTC, gnu-andrew commented
/reviewers 2 reviewer

2022-09-01 01:13 UTC, gnu-andrew approved these changes
8u-dev now open for commits.

2022-09-01 08:42 UTC, jerboaa commented
@mrserb This is not being recognized as a backport. Please use `Backport 39ec43618136abffdd071b066dc9a5d56317348b` as the PR title and it should be detected appropriately.

2022-09-07 00:22 UTC, mrserb commented
/integrate

2022-09-07 00:24 UTC, closed without merging